server:
    port: 4041
spring:
    application:
        name: MiniProject-02
    datasource:
        driverClassName: org.h2.Driver
        password: password
        url: jdbc:h2:mem:testdb
        username: sa
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
